name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality_ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.13']
        otp: ['25']

    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }}

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Install Dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix dialyzer --plt

    - name: Check quality.ci
      run: |
        mix sobelow -r apps/story_mapper
        mix quality.ci